#ifndef KOBAYAXI_PLATFORM_H_HEADER_GUARD
#define KOBAYAXI_PLATFORM_H_HEADER_GUARD



#if KOBAYAXI_PLATFORM_WIN

#elif KOBAYAXI_PLATFORM_UNIX

#endif // !KOBAYAXI_PLATFORM_WIN

#endif // !KOBAYAXI_PLATFORM_H_HEADER_GUARD